apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80 ## opcional
      nodePort: 30001 ## opcional 30000..32767 [acesso via mundo externo ao cluster]
  selector:
    app: sistema-noticias